shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

# 遅延ロード用（必須）
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# コマンド補完提案
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# 追加の補完定義
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# 補完強化
[plugins.zeno]
github = "yuki-yano/zeno.zsh"
branch = "feature/sqlite-history-subsystem"

# シンタックスハイライト
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

# ↑↓キーで履歴を部分一致検索
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

# 括弧・クォートの自動補完
[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]
